title: Little Swell
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.7942665
  rhythmicContrast: 0.5
  brandColors:
    - '#d7f8fc'
    - '#014a29'
    - '#a6c075'
    - '#79aa9b'
    - '#a2ccc2'
  lightness: 0.625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Little Swell
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.09316
layout_spectrum: 0
