layout_spectrum: 0.8727505
typography_spectrum: 0.4245746
color:
  saturation: 0.5664212
  lightness: 0.7803819
  brandStrength: 0.441096
  rhythmicContrast: 0.869016
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Little Swell
