name: Little Swell
favicon: null
layout_spectrum: 0.5038
typography_spectrum: 0.09316
title: Little Swell
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8ecf7'
    - '#f98acd'
    - '#f44b1c'
    - '#4a263e'
    - '#52bcd8'
  brandStrength: 0.7942665
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
